import React from 'react'
import Head from 'next/head'

const Layout = ( { pagina, title, children } ) => {
  return (
    <>
        <Head>
            <title>{`Test - ${pagina}`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <h1 style={{textAlign:'center', marginBottom:'50px'}}>{title}</h1>
            {children}
        </main>
    </>
  )
}

export default Layout